sudo: required
language: cpp
compiler: gcc
dist: trusty

before_script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14
