sudo: require
language: generic
compiler: gcc
dist: trusty

before_install:
  # No need to install g++-5 on trusty
  - ln -s /usr/bin/g++ /usr/bin/g++-5
  # C++14
  #- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  #- sudo apt-get update -qq

install: 
  # C++14
  #- sudo apt-get install -qq g++-5

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14
