sudo: require
language: generic
compiler: gcc
dist: trusty

before_install:
  # No need to install g++-5 on trusty, its g++ default version 
  - g++ -v
  - sudo ln -s /usr/bin/g++ /usr/bin/g++-5

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp14
